use_frameworks!

target 'UIStyleSheetIOS_Example' do
  pod 'UIStyleSheetIOS', :path => '../'

  target 'UIStyleSheetIOS_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
